### ISSUE TITLE
Error: Unable to access jarfile schemaSpy.jar

### ISSUE THREAD

**Issue by petrovitch** [Stolz/laravel-schema-spy#2]
Running Laravel 5.1

```
php artisan db:spy
Using 'mysql' connection
Error: Unable to access jarfile schemaSpy.jar
Something went wrong
```

**Comment by Stolz** [comment]
Hi @petrovitch, did you install the proper JAVA connector for your database system?

For instance, if you use MySQL you need to install [this one](http://dev.mysql.com/downloads/connector/j/).

 Then in the file `config/spy.php` you need to edit the `command` option to reflect the right path where you installed the connector.

For instance, if you installed the connector in '/home/petrovitch/schemaSpy_5.0.0.jar' the `command` option should look like:

```
 'command' => 'java -jar /home/petrovitch/schemaSpy_5.0.0.jar',
```

**Comment by wapnen** [comment]
okay but add this to the documentation maybe
